server:
  port: 8080
spring:
  application:
    name: mymomentum
  datasource:
    url: jdbc:postgresql://localhost:5432/mymomentumdb
    username: mymomentum
    password: secret123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
# Application Configuration
app:
  google:
    oauth:
      clientId: 861849830529-44mlejpcr9jjhh19qbvib8vjfbo42gea.apps.googleusercontent.com
  security:
    jwt:
      secret: U/tCUvHbDJMpu43mvYlAjG8j+3knvcP5L2L3DLU6In1+sxXLBWJMFuXlD2H+uXqj
      expirationMinutes: 60
  cors:
    allowedOrigins:
      - http://localhost:3000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.ramble.mymomentum: DEBUG

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: MyMomentum API
    description: Super momentum management API
    version: 1.0.0
    contact:
      name: Ramble Team
